source "https://rubygems.org"

# Use GitHub Pages gem which includes Jekyll and supported plugins
gem "github-pages", group: :jekyll_plugins

# Minimal Mistakes theme - remote theme for GitHub Pages
gem "jekyll-remote-theme"

# Additional plugins
gem "jekyll-include-cache"

# Windows and JRuby does not include zoneinfo files
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
